### ISSUE TITLE
Project build fails with xCode 13.0 in Release build configuration

### ISSUE THREAD

**Issue by dsk1306** [CombineCommunity/CombineExt#104]
<img width="1512" alt="Screenshot 2021-09-21 at 15 03 10" src="https://user-images.githubusercontent.com/9428706/134167187-b7814549-b481-4947-b27b-3e80b6bbc2a7.png">
<img width="1512" alt="Screenshot 2021-09-21 at 15 03 17" src="https://user-images.githubusercontent.com/9428706/134167194-2b719e82-2082-4f0a-8c0b-e8f07c7985cf.png">

**Comment by freak4pc** [comment]
This should be fixed in 1.5.0

**Comment by nikitaame** [comment]
Confirming that this is still broken after updating to 1.5.0.

**Comment by sprzenus** [comment]
The fix is 1.5.0 works for me though. Thanks!

**Comment by freak4pc** [comment]
@nikitaame can you share a simple repro project?

**Comment by dsk1306** [comment]
@nikitaame Might worth to check your project setup, `1.5.0` works fine for me with xCode 13 and Release build config.

**Comment by nikitaame** [comment]
Sorry for the confusion, this is working for me!

We have separate device and simulator workspaces for Unity and the device packages were not up to date. My apologies!

**Comment by nikitaame** [comment]
Hmm, actually, I thought this would finally work since it was finally actually using 1.5.0 but it failed again. Will try to make a sample project!
